-- View of all objects and their respective unique columns.
-- It is guaranteed no two objects in the database can share the exact same values of all unique columns,
-- thanks to the unique index for each object class.
CREATE OR REPLACE VIEW pov.pg_all_objects_unique_columns AS
SELECT
'pg_foreign_data_wrapper'::regclass::text AS class_name,
'pg_foreign_data_wrapper'::regclass::oid  AS classid,
pg_foreign_data_wrapper.oid               AS objid,
0::integer                                AS objsubid,
NULL::int2                                AS column_number,
NULL::name                                AS access_method_name,
NULL::int2                                AS operator_strategy_number,
NULL::int2                                AS support_function_number,
NULL::text                                AS support_function_name,
NULL::name                                AS attribute_name,
NULL::name                                AS role_name,
NULL::name                                AS relation_name,
NULL::text                                AS relation_kind,
NULL::name                                AS constraint_name,
NULL::name                                AS conversion_name,
NULL::name                                AS database_name,
NULL::name                                AS enumerator_name,
pg_foreign_data_wrapper.fdwname           AS foreign_data_wrapper_name,
NULL::name                                AS foreign_server_name,
NULL::name                                AS language_name,
NULL::name                                AS namespace_name,
NULL::name                                AS operator_class_name,
NULL::name                                AS operator_name,
NULL::name                                AS operator_family_name,
NULL::text                                AS function_name,
NULL::oidvector                           AS function_input_argument_types,
NULL::name                                AS rule_name,
NULL::name                                AS tablespace_name,
NULL::name                                AS trigger_name,
NULL::text                                AS data_type_name,
NULL::text                                AS source_data_type_name,
NULL::text                                AS target_data_type_name,
NULL::text                                AS left_data_type_name,
NULL::text                                AS right_data_type_name,
NULL::name                                AS text_search_configuration_name,
NULL::name                                AS text_search_dictionary_name,
NULL::name                                AS text_search_parser_name,
NULL::name                                AS text_search_template_name
FROM pg_foreign_data_wrapper
UNION ALL
SELECT
'pg_authid'::regclass::text AS class_name,
'pg_authid'::regclass::oid  AS classid,
pg_authid.oid               AS objid,
0                               AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_authid.rolname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_authid
UNION ALL
SELECT
'pg_foreign_server'::regclass::text AS class_name,
'pg_foreign_server'::regclass::oid  AS classid,
pg_foreign_server.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_foreign_server.srvname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_foreign_server
UNION ALL
SELECT
'pg_am'::regclass::text AS class_name,
'pg_am'::regclass::oid  AS classid,
pg_am.oid               AS objid,
0                  AS objsubid,
NULL,
pg_am.amname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_am
UNION ALL
SELECT
'pg_namespace'::regclass::text AS class_name,
'pg_namespace'::regclass::oid  AS classid,
pg_namespace.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_namespace
UNION ALL
SELECT
'pg_tablespace'::regclass::text AS class_name,
'pg_tablespace'::regclass::oid  AS classid,
pg_tablespace.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_tablespace.spcname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_tablespace
UNION ALL
SELECT
'pg_user_mapping'::regclass::text AS class_name,
'pg_user_mapping'::regclass::oid  AS classid,
pg_user_mapping.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_authid.rolname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_foreign_server.srvname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_user_mapping
JOIN pg_authid               ON (pg_authid.oid         = pg_user_mapping.umuser)
JOIN pg_foreign_server       ON (pg_foreign_server.oid = pg_user_mapping.umserver)
UNION ALL
SELECT
'pg_constraint'::regclass::text AS class_name,
'pg_constraint'::regclass::oid  AS classid,
pg_constraint.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_class.relname,
NULL,
pg_constraint.conname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_constraint
JOIN pg_namespace  ON (pg_namespace.oid  = pg_constraint.connamespace)
LEFT JOIN pg_class ON (pg_constraint.conrelid = pg_class.oid)
UNION ALL
SELECT
'pg_conversion'::regclass::text AS class_name,
'pg_conversion'::regclass::oid  AS classid,
pg_conversion.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_conversion.conname,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_conversion
JOIN pg_namespace  ON (pg_namespace.oid  = pg_conversion.connamespace)
UNION ALL
SELECT
'pg_opclass'::regclass::text AS class_name,
'pg_opclass'::regclass::oid  AS classid,
pg_opclass.oid               AS objid,
0                  AS objsubid,
NULL,
pg_am.amname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
pg_opclass.opcname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_opclass
JOIN pg_am        ON (pg_am.oid        = pg_opclass.opcmethod)
JOIN pg_namespace ON (pg_namespace.oid = pg_opclass.opcnamespace)
UNION ALL
SELECT
'pg_opfamily'::regclass::text AS class_name,
'pg_opfamily'::regclass::oid  AS classid,
pg_opfamily.oid               AS objid,
0                  AS objsubid,
NULL,
pg_am.amname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
pg_opfamily.opfname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_opfamily
JOIN pg_am        ON (pg_am.oid        = pg_opfamily.opfmethod)
JOIN pg_namespace ON (pg_namespace.oid = pg_opfamily.opfnamespace)
UNION ALL
SELECT
'pg_type'::regclass::text AS class_name,
'pg_type'::regclass::oid  AS classid,
pg_type.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pov._format_type(pg_catalog.pg_type.oid,NULL),
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_type
JOIN pg_namespace ON (pg_namespace.oid = pg_type.typnamespace)
UNION ALL
SELECT
'pg_enum'::regclass::text AS class_name,
'pg_enum'::regclass::oid  AS classid,
pg_enum.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_enum.enumlabel,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pov._format_type(pg_catalog.pg_type.oid,NULL),
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_enum
JOIN pg_type      ON (pg_type.oid      = pg_enum.enumtypid)
JOIN pg_namespace ON (pg_namespace.oid = pg_type.typnamespace)
UNION ALL
SELECT
'pg_cast'::regclass::text AS class_name,
'pg_cast'::regclass::oid  AS classid,
pg_cast.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pov._format_type(pg_cast.castsource,NULL),
pov._format_type(pg_cast.casttarget,NULL),
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_cast
UNION ALL
SELECT
'pg_operator'::regclass::text AS class_name,
'pg_operator'::regclass::oid  AS classid,
pg_operator.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
pg_operator.oprname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pov._format_type(pg_operator.oprleft,NULL),
pov._format_type(pg_operator.oprright,NULL),
NULL,
NULL,
NULL,
NULL
FROM pg_operator
JOIN pg_namespace ON (pg_namespace.oid = pg_operator.oprnamespace)
UNION ALL
SELECT
'pg_language'::regclass::text AS class_name,
'pg_language'::regclass::oid  AS classid,
pg_language.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_language.lanname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_language
UNION ALL
SELECT
'pg_proc'::regclass::text AS class_name,
'pg_proc'::regclass::oid  AS classid,
pg_proc.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
quote_ident(pg_proc.proname),
pg_proc.proargtypes,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_proc
JOIN pg_namespace ON (pg_namespace.oid = pg_proc.pronamespace)
UNION ALL
SELECT
'pg_ts_config'::regclass::text AS class_name,
'pg_ts_config'::regclass::oid  AS classid,
pg_ts_config.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_ts_config.cfgname,
NULL,
NULL,
NULL
FROM pg_ts_config
JOIN pg_namespace ON (pg_namespace.oid = pg_ts_config.cfgnamespace)
UNION ALL
SELECT
'pg_ts_dict'::regclass::text AS class_name,
'pg_ts_dict'::regclass::oid  AS classid,
pg_ts_dict.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_ts_dict.dictname,
NULL,
NULL
FROM pg_ts_dict
JOIN pg_namespace ON (pg_namespace.oid = pg_ts_dict.dictnamespace)
UNION ALL
SELECT
'pg_ts_parser'::regclass::text AS class_name,
'pg_ts_parser'::regclass::oid  AS classid,
pg_ts_parser.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_ts_parser.prsname,
NULL
FROM pg_ts_parser
JOIN pg_namespace ON (pg_namespace.oid = pg_ts_parser.prsnamespace)
UNION ALL
SELECT
'pg_ts_template'::regclass::text AS class_name,
'pg_ts_template'::regclass::oid  AS classid,
pg_ts_template.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_ts_template.tmplname
FROM pg_ts_template
JOIN pg_namespace   ON (pg_namespace.oid   = pg_ts_template.tmplnamespace)
UNION ALL
SELECT
'pg_amop'::regclass::text AS class_name,
'pg_amop'::regclass::oid  AS classid,
pg_amop.oid               AS objid,
0                  AS objsubid,
NULL,
pg_am.amname,
pg_amop.amopstrategy,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
pg_operator.oprname,
pg_opfamily.opfname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pov._format_type(pg_operator.oprleft,NULL),
pov._format_type(pg_operator.oprright,NULL),
NULL,
NULL,
NULL,
NULL
FROM pg_amop
JOIN pg_opfamily                         ON (pg_opfamily.oid  = pg_amop.amopfamily)
JOIN pg_am                               ON (pg_am.oid        = pg_opfamily.opfmethod)
JOIN pg_operator                         ON (pg_operator.oid  = pg_amop.amopopr)
JOIN pg_namespace                        ON (pg_namespace.oid = pg_operator.oprnamespace AND pg_namespace.oid = pg_opfamily.opfnamespace)
UNION ALL
SELECT
'pg_amproc'::regclass::text AS class_name,
'pg_amproc'::regclass::oid  AS classid,
pg_amproc.oid               AS objid,
0                  AS objsubid,
NULL,
pg_am.amname,
NULL,
pg_amproc.amprocnum,
pg_amproc.amproc::regprocedure::text,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
pg_opfamily.opfname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_amproc
JOIN pg_opfamily             ON (pg_opfamily.oid             = pg_amproc.amprocfamily)
JOIN pg_am                   ON (pg_am.oid                   = pg_opfamily.opfmethod)
JOIN pg_namespace            ON (pg_namespace.oid            = pg_opfamily.opfnamespace)
UNION ALL
SELECT
'pg_database'::regclass::text AS class_name,
'pg_database'::regclass::oid  AS classid,
pg_database.oid               AS objid,
0                             AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_database.datname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_database
UNION ALL
SELECT
'pg_class'::regclass::text AS class_name,
'pg_class'::regclass::oid  AS classid,
pg_class.oid               AS objid,
0                          AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_class.relname,
CASE pg_class.relkind WHEN 'c' THEN 'composite type' WHEN 'i' THEN 'index' WHEN 'r' THEN 'table' WHEN 't' THEN 'toast table' WHEN 'v' THEN 'view' WHEN 'S' THEN 'sequence' END::text,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_class
JOIN pg_namespace ON (pg_namespace.oid      = pg_class.relnamespace)
UNION ALL
SELECT
'pg_class'::regclass::text AS class_name,
'pg_class'::regclass::oid  AS classid,
pg_class.oid               AS objid,
pg_attribute.attnum        AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_attribute.attname,
NULL,
pg_class.relname,
CASE pg_class.relkind WHEN 'c' THEN 'composite type' WHEN 'i' THEN 'index' WHEN 'r' THEN 'table' WHEN 't' THEN 'toast table' WHEN 'v' THEN 'view' WHEN 'S' THEN 'sequence' END::text,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_class
JOIN pg_namespace ON (pg_namespace.oid      = pg_class.relnamespace)
JOIN pg_attribute ON (pg_attribute.attrelid = pg_class.oid)
UNION ALL
SELECT
'pg_attrdef'::regclass::text AS class_name,
'pg_attrdef'::regclass::oid  AS classid,
pg_attrdef.oid               AS objid,
0                            AS objsubid,
pg_attrdef.adnum,
NULL,
NULL,
NULL,
NULL,
pg_attribute.attname,
NULL,
pg_class.relname,
CASE pg_class.relkind WHEN 'c' THEN 'composite type' WHEN 'i' THEN 'index' WHEN 'r' THEN 'table' WHEN 't' THEN 'toast table' WHEN 'v' THEN 'view' WHEN 'S' THEN 'sequence' END::text,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_attrdef
JOIN pg_class     ON (pg_class.oid        = pg_attrdef.adrelid)
JOIN pg_namespace ON (pg_namespace.oid      = pg_class.relnamespace)
JOIN pg_attribute ON (pg_attribute.attrelid = pg_class.oid AND pg_attribute.attnum::integer = pg_attrdef.adnum)
UNION ALL
SELECT
'pg_rewrite'::regclass::text AS class_name,
'pg_rewrite'::regclass::oid  AS classid,
pg_rewrite.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_class.relname,
CASE pg_class.relkind WHEN 'c' THEN 'composite type' WHEN 'i' THEN 'index' WHEN 'r' THEN 'table' WHEN 't' THEN 'toast table' WHEN 'v' THEN 'view' END::text,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_rewrite.rulename,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_rewrite
JOIN pg_class     ON (pg_class.oid     = pg_rewrite.ev_class)
JOIN pg_namespace ON (pg_namespace.oid = pg_class.relnamespace)
UNION ALL
SELECT
'pg_trigger'::regclass::text AS class_name,
'pg_trigger'::regclass::oid  AS classid,
pg_trigger.oid               AS objid,
0                  AS objsubid,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_class.relname,
CASE pg_class.relkind WHEN 'c' THEN 'composite type' WHEN 'i' THEN 'index' WHEN 'r' THEN 'table' WHEN 't' THEN 'toast table' WHEN 'v' THEN 'view' END::text,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_trigger.tgname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM pg_trigger
JOIN pg_class     ON (pg_class.oid     = pg_trigger.tgrelid)
JOIN pg_namespace ON (pg_namespace.oid = pg_class.relnamespace)
;
