CREATE OR REPLACE FUNCTION pov.pg_unique_object_columns(
IN oid,
IN oid,
IN integer,
OUT class_name text,
OUT classid oid,
OUT objid oid,
OUT objsubid integer,
OUT access_method_name name,
OUT operator_strategy_number int2,
OUT support_function_number int2,
OUT support_function_name text,
OUT attribute_name name,
OUT role_name name,
OUT relation_name name,
OUT relation_kind text,
OUT constraint_name name,
OUT conversion_name name,
OUT database_name name,
OUT enumerator_name name,
OUT foreign_data_wrapper_name name,
OUT foreign_server_name name,
OUT language_name name,
OUT namespace_name name,
OUT operator_class_name name,
OUT operator_name name,
OUT operator_family_name name,
OUT function_name text,
OUT function_input_argument_types oidvector,
OUT rule_name name,
OUT tablespace_name name,
OUT trigger_name name,
OUT data_type_name text,
OUT source_data_type_name text,
OUT target_data_type_name text,
OUT left_data_type_name text,
OUT right_data_type_name text,
OUT text_search_configuration_name name,
OUT text_search_dictionary_name name,
OUT text_search_parser_name name,
OUT text_search_template_name name
) RETURNS RECORD AS $BODY$
WITH
object AS (
SELECT $1 AS class_id, $2 AS object_id, $3 AS object_sub_id
),
object_info AS (
SELECT
object.class_id::regclass::text AS class_name,
object.class_id::oid            AS classid,
object.object_id::oid           AS objid,
object.object_sub_id::integer   AS objsubid,
NULL::name                      AS access_method_name,
NULL::int2                      AS operator_strategy_number,
NULL::int2                      AS support_function_number,
NULL::text                      AS support_function_name,
NULL::name                      AS attribute_name,
NULL::name                      AS role_name,
NULL::name                      AS relation_name,
NULL::text                      AS relation_kind,
NULL::name                      AS constraint_name,
NULL::name                      AS conversion_name,
NULL::name                      AS database_name,
NULL::name                      AS enumerator_name,
pg_foreign_data_wrapper.fdwname AS foreign_data_wrapper_name,
NULL::name                      AS foreign_server_name,
NULL::name                      AS language_name,
NULL::name                      AS namespace_name,
NULL::name                      AS operator_class_name,
NULL::name                      AS operator_name,
NULL::name                      AS operator_family_name,
NULL::text                      AS function_name,
NULL::oidvector                 AS function_input_argument_types,
NULL::name                      AS rule_name,
NULL::name                      AS tablespace_name,
NULL::name                      AS trigger_name,
NULL::text                      AS data_type_name,
NULL::text                      AS source_data_type_name,
NULL::text                      AS target_data_type_name,
NULL::text                      AS left_data_type_name,
NULL::text                      AS right_data_type_name,
NULL::name                      AS text_search_configuration_name,
NULL::name                      AS text_search_dictionary_name,
NULL::name                      AS text_search_parser_name,
NULL::name                      AS text_search_template_name
FROM object
JOIN pg_foreign_data_wrapper ON (object.class_id = 'pg_foreign_data_wrapper'::regclass AND pg_foreign_data_wrapper.oid = object.object_id)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_authid.rolname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_authid               ON (object.class_id = 'pg_authid'::regclass               AND pg_authid.oid               = object.object_id)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_foreign_server.srvname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_foreign_server       ON (object.class_id = 'pg_foreign_server'::regclass       AND pg_foreign_server.oid       = object.object_id)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
pg_am.amname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_am                   ON (object.class_id = 'pg_am'::regclass                   AND pg_am.oid                   = object.object_id)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_namespace            ON (object.class_id = 'pg_namespace'::regclass            AND pg_namespace.oid            = object.object_id)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_tablespace.spcname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_tablespace           ON (object.class_id = 'pg_tablespace'::regclass           AND pg_tablespace.oid           = object.object_id)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_authid.rolname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_foreign_server.srvname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_user_mapping         ON (object.class_id = 'pg_user_mapping'::regclass AND pg_user_mapping.oid   = object.object_id)
JOIN pg_authid               ON (object.class_id = 'pg_user_mapping'::regclass AND pg_authid.oid         = pg_user_mapping.umuser)
JOIN pg_foreign_server       ON (object.class_id = 'pg_user_mapping'::regclass AND pg_foreign_server.oid = pg_user_mapping.umserver)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_class.relname,
NULL,
pg_constraint.conname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_constraint ON (object.class_id = 'pg_constraint'::regclass AND pg_constraint.oid = object.object_id)
JOIN pg_namespace  ON (object.class_id = 'pg_constraint'::regclass AND pg_namespace.oid  = pg_constraint.connamespace)
LEFT JOIN pg_class ON (pg_constraint.conrelid = pg_class.oid)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_conversion.conname,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_conversion ON (object.class_id = 'pg_conversion'::regclass AND pg_conversion.oid = object.object_id)
JOIN pg_namespace  ON (object.class_id = 'pg_conversion'::regclass AND pg_namespace.oid  = pg_conversion.connamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
pg_am.amname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
pg_opclass.opcname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_opclass   ON (object.class_id = 'pg_opclass'::regclass AND pg_opclass.oid   = object.object_id)
JOIN pg_am        ON (object.class_id = 'pg_opclass'::regclass AND pg_am.oid        = pg_opclass.opcmethod)
JOIN pg_namespace ON (object.class_id = 'pg_opclass'::regclass AND pg_namespace.oid = pg_opclass.opcnamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
pg_am.amname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
pg_opfamily.opfname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_opfamily  ON (object.class_id = 'pg_opfamily'::regclass AND pg_opfamily.oid  = object.object_id)
JOIN pg_am        ON (object.class_id = 'pg_opfamily'::regclass AND pg_am.oid        = pg_opfamily.opfmethod)
JOIN pg_namespace ON (object.class_id = 'pg_opfamily'::regclass AND pg_namespace.oid = pg_opfamily.opfnamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pov._format_type(pg_catalog.pg_type.oid,NULL),
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_type      ON (object.class_id = 'pg_type'::regclass AND pg_type.oid      = object.object_id)
JOIN pg_namespace ON (object.class_id = 'pg_type'::regclass AND pg_namespace.oid = pg_type.typnamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_enum.enumlabel,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pov._format_type(pg_catalog.pg_type.oid,NULL),
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_enum      ON (object.class_id = 'pg_enum'::regclass AND pg_enum.oid      = object.object_id)
JOIN pg_type      ON (object.class_id = 'pg_enum'::regclass AND pg_type.oid      = pg_enum.enumtypid)
JOIN pg_namespace ON (object.class_id = 'pg_enum'::regclass AND pg_namespace.oid = pg_type.typnamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pov._format_type(pg_cast.castsource,NULL),
pov._format_type(pg_cast.casttarget,NULL),
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_cast ON (object.class_id = 'pg_cast'::regclass AND pg_cast.oid = object.object_id)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
pg_operator.oprname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pov._format_type(pg_operator.oprleft,NULL),
pov._format_type(pg_operator.oprright,NULL),
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_operator  ON (object.class_id = 'pg_operator'::regclass AND pg_operator.oid  = object.object_id)
JOIN pg_namespace ON (object.class_id = 'pg_operator'::regclass AND pg_namespace.oid = pg_operator.oprnamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_language.lanname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_language ON (object.class_id = 'pg_language'::regclass AND pg_language.oid = object.object_id)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
quote_ident(pg_proc.proname),
pg_proc.proargtypes,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_proc      ON (object.class_id = 'pg_proc'::regclass AND pg_proc.oid      = object.object_id)
JOIN pg_namespace ON (object.class_id = 'pg_proc'::regclass AND pg_namespace.oid = pg_proc.pronamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_ts_config.cfgname,
NULL,
NULL,
NULL
FROM object
JOIN pg_ts_config ON (object.class_id = 'pg_ts_config'::regclass AND pg_ts_config.oid = object.object_id)
JOIN pg_namespace ON (object.class_id = 'pg_ts_config'::regclass AND pg_namespace.oid = pg_ts_config.cfgnamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_ts_dict.dictname,
NULL,
NULL
FROM object
JOIN pg_ts_dict   ON (object.class_id = 'pg_ts_dict'::regclass AND pg_ts_dict.oid   = object.object_id)
JOIN pg_namespace ON (object.class_id = 'pg_ts_dict'::regclass AND pg_namespace.oid = pg_ts_dict.dictnamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_ts_parser.prsname,
NULL
FROM object
JOIN pg_ts_parser ON (object.class_id = 'pg_ts_parser'::regclass AND pg_ts_parser.oid = object.object_id)
JOIN pg_namespace ON (object.class_id = 'pg_ts_parser'::regclass AND pg_namespace.oid = pg_ts_parser.prsnamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_ts_template.tmplname
FROM object
JOIN pg_ts_template ON (object.class_id = 'pg_ts_template'::regclass AND pg_ts_template.oid = object.object_id)
JOIN pg_namespace   ON (object.class_id = 'pg_ts_template'::regclass AND pg_namespace.oid   = pg_ts_template.tmplnamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
pg_am.amname,
pg_amop.amopstrategy,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
pg_operator.oprname,
pg_opfamily.opfname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pov._format_type(pg_operator.oprleft,NULL),
pov._format_type(pg_operator.oprright,NULL),
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_amop                             ON (object.class_id = 'pg_amop'::regclass AND pg_amop.oid      = object.object_id)
JOIN pg_opfamily                         ON (object.class_id = 'pg_amop'::regclass AND pg_opfamily.oid  = pg_amop.amopfamily)
JOIN pg_am                               ON (object.class_id = 'pg_amop'::regclass AND pg_am.oid        = pg_opfamily.opfmethod)
JOIN pg_operator                         ON (object.class_id = 'pg_amop'::regclass AND pg_operator.oid  = pg_amop.amopopr)
JOIN pg_namespace                        ON (object.class_id = 'pg_amop'::regclass AND pg_namespace.oid = pg_operator.oprnamespace AND pg_namespace.oid = pg_opfamily.opfnamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
pg_am.amname,
NULL,
pg_amproc.amprocnum,
pg_amproc.amproc::regprocedure::text,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
pg_opfamily.opfname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_amproc               ON (object.class_id = 'pg_amproc'::regclass AND pg_amproc.oid               = object.object_id)
JOIN pg_opfamily             ON (object.class_id = 'pg_amproc'::regclass AND pg_opfamily.oid             = pg_amproc.amprocfamily)
JOIN pg_am                   ON (object.class_id = 'pg_amproc'::regclass AND pg_am.oid                   = pg_opfamily.opfmethod)
JOIN pg_namespace            ON (object.class_id = 'pg_amproc'::regclass AND pg_namespace.oid            = pg_opfamily.opfnamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_database.datname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_database ON (object.class_id = 'pg_database'::regclass AND pg_database.oid = object.object_id)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
pg_attribute.attname,
NULL,
pg_class.relname,
CASE pg_class.relkind WHEN 'c' THEN 'composite type' WHEN 'i' THEN 'index' WHEN 'r' THEN 'table' WHEN 't' THEN 'toast table' WHEN 'v' THEN 'view' WHEN 'S' THEN 'sequence' END::text,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_class          ON (object.class_id = 'pg_class'::regclass AND pg_class.oid          = object.object_id)
JOIN pg_namespace      ON (object.class_id = 'pg_class'::regclass AND pg_namespace.oid      = pg_class.relnamespace)
LEFT JOIN pg_attribute ON (object.class_id = 'pg_class'::regclass AND pg_attribute.attrelid = pg_class.oid AND pg_attribute.attnum::integer = object.object_sub_id)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
pg_attribute.attname,
NULL,
pg_class.relname,
CASE pg_class.relkind WHEN 'c' THEN 'composite type' WHEN 'i' THEN 'index' WHEN 'r' THEN 'table' WHEN 't' THEN 'toast table' WHEN 'v' THEN 'view' WHEN 'S' THEN 'sequence' END::text,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_attrdef   ON (object.class_id = 'pg_attrdef'::regclass AND pg_attrdef.oid      = object.object_id)
JOIN pg_class     ON (object.class_id = 'pg_attrdef'::regclass AND pg_class.oid        = pg_attrdef.adrelid)
JOIN pg_namespace ON (object.class_id = 'pg_attrdef'::regclass AND pg_namespace.oid      = pg_class.relnamespace)
JOIN pg_attribute ON (object.class_id = 'pg_attrdef'::regclass AND pg_attribute.attrelid = pg_class.oid AND pg_attribute.attnum::integer = pg_attrdef.adnum)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_class.relname,
CASE pg_class.relkind WHEN 'c' THEN 'composite type' WHEN 'i' THEN 'index' WHEN 'r' THEN 'table' WHEN 't' THEN 'toast table' WHEN 'v' THEN 'view' END::text,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_rewrite.rulename,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_rewrite   ON (object.class_id = 'pg_rewrite'::regclass AND pg_rewrite.oid   = object.object_id)
JOIN pg_class     ON (object.class_id = 'pg_rewrite'::regclass AND pg_class.oid     = pg_rewrite.ev_class)
JOIN pg_namespace ON (object.class_id = 'pg_rewrite'::regclass AND pg_namespace.oid = pg_class.relnamespace)
UNION ALL
SELECT
object.class_id::regclass::text,
object.class_id,
object.object_id,
object.object_sub_id,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_class.relname,
CASE pg_class.relkind WHEN 'c' THEN 'composite type' WHEN 'i' THEN 'index' WHEN 'r' THEN 'table' WHEN 't' THEN 'toast table' WHEN 'v' THEN 'view' END::text,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_namespace.nspname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
pg_trigger.tgname,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM object
JOIN pg_trigger   ON (object.class_id = 'pg_trigger'::regclass AND pg_trigger.oid   = object.object_id)
JOIN pg_class     ON (object.class_id = 'pg_trigger'::regclass AND pg_class.oid     = pg_trigger.tgrelid)
JOIN pg_namespace ON (object.class_id = 'pg_trigger'::regclass AND pg_namespace.oid = pg_class.relnamespace)
)
SELECT * FROM object_info;
$BODY$ LANGUAGE sql STABLE;
